import type { Member } from "@/lib/types";
import type { Timestamp } from "@/lib/types/firestore";

function mockTimestamp(date: Date = new Date()): Timestamp {
  return {
    toDate: () => date,
    toMillis: () => date.getTime(),
    seconds: Math.floor(date.getTime() / 1000),
    nanoseconds: (date.getTime() % 1000) * 1000000,
  };
}

const now = mockTimestamp();

export const mockMembers: Member[] = [
  {
    id: "mem-1",
    username: "ruthvik",
    displayName: "Devidi Ruthvik Reddy",
    email: "ruthvik@vjit.ac.in",
    photoURL: null,
    role: "core",
    team: "Core",
    cohortYear: 2024,
    batchYear: 2027,
    branch: "CSE",
    bio: "Leading the AWS Cloud Club VJIT's mission to build the next generation of cloud professionals.",
    skills: ["AWS", "Cloud Architecture", "Leadership", "Public Speaking"],
    socials: { linkedin: "#", github: "#", twitter: "#" },
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mem-2",
    username: "vedant",
    displayName: "Vedant M Idlgave",
    email: "vedant@vjit.ac.in",
    photoURL: null,
    role: "core",
    team: "Tech",
    cohortYear: 2024,
    batchYear: 2027,
    branch: "CSE",
    bio: "Building the infrastructure and leading all technical initiatives. Cloud builder and open-source enthusiast.",
    skills: ["Next.js", "TypeScript", "AWS CDK", "Serverless", "Terraform"],
    socials: { linkedin: "#", github: "#", twitter: "#" },
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mem-3",
    username: "srujan",
    displayName: "Sai Srujan",
    email: "srujan@vjit.ac.in",
    photoURL: null,
    role: "lead",
    team: "Events",
    cohortYear: 2024,
    batchYear: 2027,
    branch: "IT",
    bio: "Orchestrating workshops, hackathons, and community events to spread cloud knowledge.",
    skills: ["Event Operations", "AWS", "Logistics", "Community Outreach"],
    socials: { linkedin: "#", github: "#" },
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mem-4",
    username: "jithendra",
    displayName: "Jithendra",
    email: "jithendra@vjit.ac.in",
    photoURL: null,
    role: "lead",
    team: "Production",
    cohortYear: 2024,
    batchYear: 2027,
    branch: "CSE",
    bio: "Managing content production, videography, and event documentation for AWS Cloud Club.",
    skills: ["Video Production", "Content Strategy", "Digital Media", "AWS Educate"],
    socials: { linkedin: "#", github: "#" },
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mem-5",
    username: "medha",
    displayName: "Sai Medha",
    email: "medha@vjit.ac.in",
    photoURL: null,
    role: "lead",
    team: "Design",
    cohortYear: 2024,
    batchYear: 2027,
    branch: "CSE",
    bio: "Crafting the visual identity, website designs, and creative direction of the club.",
    skills: ["UI/UX", "Figma", "Branding", "Graphic Design"],
    socials: { linkedin: "#", github: "#" },
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "mem-6",
    username: "sameera",
    displayName: "Sameera K",
    email: "sameera@vjit.ac.in",
    photoURL: null,
    role: "lead",
    team: "Marketing",
    cohortYear: 2024,
    batchYear: 2027,
    branch: "AI&DS",
    bio: "Passionate about marketing, data analysis, and AI deployments. Leading marketing initiatives for the club.",
    skills: ["Data Analytics", "AWS S3", "Athena", "SQL", "Marketing", "Social Media"],
    socials: { linkedin: "#", github: "#" },
    isPublic: true,
    createdAt: now,
    updatedAt: now,
  },
];
